positive_mirnas = ["hsa-mir-143",
                   "hsa-mir-144",
                   "hsa-mir-145",
                   "hsa-mir-146a",
                   "hsa-mir-146b",
                   "hsa-mir-155",
                   "hsa-mir-15a",
                   "hsa-mir-17",
                   "hsa-mir-181a",
                   "hsa-mir-19a",
                   "hsa-mir-19b",
                   "hsa-mir-20a",
                   "hsa-mir-210",
                   "hsa-mir-27b",
                   "hsa-mir-34a",
                   "hsa-mir-451b",
                   "hsa-mir-92a"]

random_mirnas = ["hsa-mir-1250",
                 "hsa-mir-329",
                 "hsa-mir-371b",
                 "hsa-mir-378h",
                 "hsa-mir-379",
                 "hsa-mir-449c",
                 "hsa-mir-4517",
                 "hsa-mir-4695",
                 "hsa-mir-4804",
                 "hsa-mir-5002",
                 "hsa-mir-5100",
                 "hsa-mir-5584",
                 "hsa-mir-6510",
                 "hsa-mir-6782",
                 "hsa-mir-6794",
                 "hsa-mir-6827",
                 "hsa-mir-7855"]

all_mirnas = positive_mirnas + random_mirnas
interaction_file = "mirdb_interactions_m17_training.csv"
